const CREATE_TODOITEM_TYPE = "todolist/CREATE_TODOITEM_TYPE"
const DELETE_TODOITEM_TYPE = "todolist/DELETE_TODOITEM_TYPE"
const TOGGLE_TODOITEM_TYPE = "todolist/TOGGLE_TODOITEM_TYPE"
const SELALL_TODOITEM_TYPE = "todolist/SELALL_TODOITEM_TYPE"
export { CREATE_TODOITEM_TYPE, DELETE_TODOITEM_TYPE, TOGGLE_TODOITEM_TYPE, SELALL_TODOITEM_TYPE }